import Head from 'next/head'
import {ethers} from "ethers";
import styles from '@/styles/Home.module.css'
import styled from "styled-components";
import {useRouter} from "next/router";
import {useAppDispatch} from "@/store";
import {setAccount} from "@/store/accountSlice";
import {useEffect} from "react";

const Title = styled.h1`
  color: red;
`;

export default function Home() {
    const router = useRouter();
    const dispatch = useAppDispatch()

    const handleButton = async () => {
        const provider = new ethers.BrowserProvider(window.ethereum!)
        const accounts = await provider.send("eth_requestAccounts", []);
        const address = accounts[0]
        localStorage.setItem('address', address)
        dispatch(setAccount(address))
        router.push('/assets')
    }

    useEffect(() => {
        const localAddress = localStorage.getItem('address')
        if (localAddress) {
            dispatch(setAccount(localAddress))
            router.push('/assets')
        }
    }, [dispatch, router])

    return (
        <>
            <Head>
                <title>Balancer</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <button onClick={handleButton}>
                    <Title>AUE</Title>
                </button>
            </main>
        </>
    )
}
